### ISSUE TITLE
Python 3.5 regression

### ISSUE THREAD

**Issue by joe-graham-oag** [geopandas/contextily#149]
![image](https://user-images.githubusercontent.com/54988691/81833338-9418fb00-950d-11ea-8844-e6b2f6eba0dd.png)
Importing contextily on Python 3.5 results in this syntax error due to the use of f-strings, which were introduced in Python 3.6.

**Comment by darribas** [comment]
Hello, thanks for the report! 

Yes, that's correct, we only support 3.6 and above ([currently testing](https://github.com/geopandas/contextily/blob/master/.travis.yml#L10) on 3.6 and 3.7).

**Comment by joe-graham-oag** [comment]
That would be appreciated, as well as changing the python_requires field in [setup.py](https://github.com/geopandas/contextily/blob/master/setup.py).

**Comment by darribas** [comment]
Thanks! PR issued over at #150. Should be on `master` soon
