### ISSUE TITLE
Centralise XYZ services?

### ISSUE THREAD

**Issue by darribas** [geopandas/contextily#153]
Playing with `xarray-leaflet` I realised `ipyleaflet` supports a similar set of providers than us and seems to hand-code the providers in a similar way to how we do it:

https://github.com/jupyter-widgets/ipyleaflet/blob/master/ipyleaflet/basemaps.py

This has got me thinking if there's scope to join forces into a small library (`xyzervices`?) that parses a large amount of XYZ providers in a way that is useful to the Python data community. From the looks of it, other libraries could also use it and we'd only need to edit providers in one place for everyone to benefit.

Would this make sense? @jorisvandenbossche, @SylvainCorlay, @davidbrochart

**Comment by davidbrochart** [comment]
cc @martinRenou

**Comment by martinRenou** [comment]
I love the idea. Thanks for bringing that up.

> We use traitlets's Bunch, but we could have a no-dependency structure in this new library and transform it in ipyleaflet.

What's really nice about the `Bunch` data structure is that, unlike a simple dictionary, it provides completion in IPython so people can quickly look at what's available inside the structure. But we can definitely re-implement this data structure in this new library, it's not too much code duplication.

**Comment by jorisvandenbossche** [comment]
When I wrote the new providers module in contextily, it was actually inspired on ipyleaflet (I know I had the same thought about potentially sharing this as well, but forgot to open an issue about it back then, thanks Dani!). 

So if you look at the providers code in contextily (https://github.com/geopandas/contextily/blob/master/contextily/_providers.py), you will see it also uses a "Bunch". Which is basically the same as the one of traitlets, but hardcoded (so indeed adding attribute access to the dictionary, and in addition I also added  `__call__` to pass custom values to the actual Providers):

 https://github.com/geopandas/contextily/blob/0d1413ee77f799a1985ae66dc3c250de7621ede8/contextily/_providers.py#L16-L38

**Comment by martinRenou** [comment]
Nice. We would definitely make sense to share this.

**Comment by darribas** [comment]
Nice! What would be a good approach? A few questions to think through:

- My sense is ideally we'd set a separate mini package (`xyzservices` or something like that) which we can all "consume" from
- If so, I haven't looked in detail, but what'd be the specs/API be required for a service?
- Initially, we could start with the list of leaflet providers we have in `ipyleaflet`/`contextily` (I think right now it's the same)
- Going forward, another benefit of a package like this would be to be able to take arbitrary contributions from other services, so we are not limited to what leaflet offers. As long as we had a clear spec of the format expected, it should be easy to provide a structure that allows to merge an automated list from leaflet and a manual one community contributed, and expose the two as one big list to the end-user
- Also, where should this package live?

Does this sound sensible? Maybe let's flesh out more details on this issue so, when somebody has bandwith, it's easy to pick up coding?

**Comment by martinRenou** [comment]
> If so, I haven't looked in detail, but what'd be the specs/API be required for a service?

I guess a good approach would be to look at what you need for each element of the bunch in geopandas, look at what we need in ipyleaflet, and merge the results.

What we need in ipyleaflet is:
- url
- name
- attribution
- min_zoom (optional)
- max_zoom (optional)

Also some urls contain a `%` that we replace by the date (e.g. when the satellite images were taken) in our Python API: https://github.com/jupyter-widgets/ipyleaflet/blob/master/ipyleaflet/leaflet.py#L46

> Initially, we could start with the list of leaflet providers we have in ipyleaflet/contextily (I think right now it's the same)

I feel like there is a bit more in contextily, but again merging both would be the best approach I guess.

**Comment by jorisvandenbossche** [comment]
All those listed keys are available in the providers defined here in contextily (again, the dict structure is actually based on ipyleaflet ;), and all values are obtained from scraping leaflet-providers https://github.com/leaflet-extras/leaflet-providers). 
Have a look at https://github.com/geopandas/contextily/blob/master/contextily/_providers.py to see if that looks OK. I think url/name/attribution should be present for each of the providers

One potential problem is the attribution: in contextily we stripped them from all html code (https://github.com/geopandas/contextily/blob/master/scripts/parse_leaflet_providers.py#L121), while keeping this probably makes sense for ipyleaflet. 
Now, it should not be a problem to preserve that in the original ones, and then we can do the stripping in contextily (or add a `attribution_text` key with the stripped version that contextily can use).

For the date, this is done with a `/{time}/` in the url (at least for the NASA example you gave), so the `url % day` in ipyleaflet could be replaced with `url.format(time=day)`, I think (or actually updating the provider with `provider = provider(time=day)`, if it has a time key). 
Would that work for ipyleaflet?

So if ipyleaflet would happy to use this, I think it would basically entail:

- move the `contextily/_tile_providers.py` + the script to generate it to a new package almost as is
- add the few ones that ipyleaflet has and contextily not (from a quick look, I think this is only the Strava ones). For this, we need to implement a bit of code to merge the autogenerated ones with a set of manually added ones.

**Comment by davidbrochart** [comment]
> For the date, this is done with a `/{time}/` in the url (at least for the NASA example you gave), so the `url % day` in ipyleaflet could be replaced with `url.format(time=day)`, I think (or actually updating the provider with `provider = provider(time=day)`, if it has a time key).
> Would that work for ipyleaflet?

Yes, in any case we can update our code it there is any change in how we insert the date.

> So if ipyleaflet would happy to use this, I think it would basically entail:
> 
>     * move the `contextily/_tile_providers.py` + the script to generate it to a new package almost as is
> 
>     * add the few ones that ipyleaflet has and contextily not (from a quick look, I think this is only the Strava ones). For this, we need to implement a bit of code to merge the autogenerated ones with a set of manually added ones.

Let's get started with this.

**Comment by davidbrochart** [comment]
> * Where'd we host this? Would the `geopandas`/`jupyter`/other orgs be a good home for the project? A separate one?

I think hosting it in `geopandas` makes more sense than in `jupyter`.

**Comment by davidbrochart** [comment]
It looks like we are all too busy to work on this. Should we drop the idea or keep it open? We'd like to move forward with https://github.com/jupyter-widgets/ipyleaflet/issues/741.

**Comment by darribas** [comment]
Hello, thanks for the post and checking in. I'm very low on bandwith atm (term time in corona days does not leave much coding time...) and would not want to delay any progress on your end. If any of those ideas could be developed outside ipyleaflet so we can consume in other libs like `contextily`, it'd be fantastic. I can help on that front but leading on it is unlikely.

In reading #741 it occurred to me that a start to centralise basemaps could be a JSON file that could be imported on `ipyleaflet`/`xleaflet` and that we can also work with in `contextily`. Over time we can work on tooling to automate the generation of that file and how we can take further sources from places other than leaflet.

I'm sorry I can't commit to more right now, I'm just over-stretched.

**Comment by davidbrochart** [comment]
No worries @darribas!
So yes we could start by simply implementing https://github.com/jupyter-widgets/ipyleaflet/issues/741 in a separate repository, and build up from there. Thanks!

**Comment by martinfleis** [comment]
A quick update on this. @darribas and I plan to do a coding sprint on this by the end of the next month, starting from the current `contextily._providers` module and including features like #172 and #171.

One thing I'd like to understand before that is the best way of storing the basemap metadata. At the moment, we have them hard-coded in a (generated) `Bunch` object 
https://github.com/geopandas/contextily/blob/799c70802892f0276ace74159df3ed24779cedbf/contextily/_providers.py#L41-L48

However, reading through https://github.com/jupyter-widgets/ipyleaflet/issues/741 and the discussion above, one option which came to my mind is to store them as JSON and create the `Bunch` on initialization (should be lightweight script anyway). In that way, we still have the Python object with completion in Jupyter and generic JSON anyone can ingest and use, even without Python in their environment (i.e. linking it directly from repo).

Also, if there are some updates in ipyleaflet or elsewhere that should be taken into the account, let us know.

**Comment by davidbrochart** [comment]
> store them as JSON and create the `Bunch` on initialization

That would be great.

**Comment by martinRenou** [comment]
One idea brought by @SylvainCorlay in https://github.com/jupyter-widgets/ipyleaflet/issues/741 was that we could install this JSON file under `/share`

To answer to your question in this issue @jorisvandenbossche:

> > JSON data from a share/jupyter/leaflet/basemaps directory...

> To understand better, what would be the exact idea of the above? Is this something that already exists from the leaflet installation, or is it something that ipyleaflet (or another package) would generate and install, so it is usable by ipyleaflet itself and other packages like xleaflet?

It's something that this `xyzervices` would install, so maybe we could install this JSON file under `share/xyzervices`? This way the JSON file is discoverable to other libraries, and it also allows users to update this JSON file or provide their own.

**Comment by martinfleis** [comment]
I like this idea (not that I know how to do that atm). To use the JSON you just need to ensure that `xyzservices` is installed but no need to import it or fetch it from the web.

**Comment by martinfleis** [comment]
The work on the package has begun at https://github.com/geopandas/xyzservices. Please express any wishes we did not cover yet (either in code or in issue) as an issue in the repo. At the moment, we store providers in JSON and mimic the behaviour of `contextily.providers` module.

**Comment by martinfleis** [comment]
We're moving to the next phase with this. `xyzservices` has been released! https://xyzservices.readthedocs.io/en/latest/

During the following days, I'll try to open issues in respective packages to start a discussion on how to use it in the most efficient way. Thanks a lot for this discussion - now let's move it to https://github.com/geopandas/xyzservices. 🎉
