### ISSUE TITLE
crs option of contextily.add_basemap not working on WSL

### ISSUE THREAD

**Issue by longavailable** [geopandas/contextily#159]
As the title, I tried to add a base map with `crs` option of `contextily.add_basemap` on wsl. While it returned `segmentation fault (core dumped)  python3`.

![error](https://user-images.githubusercontent.com/24582280/93795880-52762a80-fc3a-11ea-8dd2-581c268eba6d.png)

 The example is from [Convert both datasets into a different CRS](https://contextily.readthedocs.io/en/latest/warping_guide.html#Convert-both-datasets-into-a-different-CRS).

Any suggestion?

**Comment by jorisvandenbossche** [comment]
@longavailable Thanks for the report! Fix is being prepared at  #163
