### ISSUE TITLE
Add new Strava tiles

### ISSUE THREAD

**Issue by darribas** [geopandas/contextily#16]
Following a [comment](https://medium.com/@paalped/this-is-by-far-the-most-beautiful-maps-out-there-655d45c458a3) on the announcement, the new tiles are served at:

> https://heatmap-external-a.strava.com/tiles/all/hot/tileZ/tileX/tileY.png
> https://heatmap-external-b.strava.com/tiles/all/gray/tileZ/tileX/tileY.png
> https://heatmap-external-b.strava.com/tiles/all/bluered/tileZ/tileX/tileY.png

This seems to work with our current infrastructure to access remote tiles through the `url` argument.

**Comment by martinfleis** [comment]
Resolved by xyzservices.
