### ISSUE TITLE
Update for latest versions of gdal and fiona?

### ISSUE THREAD

**Issue by pythonic2020** [geopandas/contextily#176]
Hi, I was wondering if there are any plans to update contextily dependencies so that it can work with latest versions of gdal (3.2.2) and fiona (1.8.19)?  Everything works great now, but installing contextily into a conda-forge environment necessitates downgrading gdal and fiona substantially (to gdal 3.1.4 and fiona 1.8.18).

**Comment by jorisvandenbossche** [comment]
Can you give some more details? Eg example output of installing contextily / creating an environment, and which dependencies it requires? 

Contextily itself is a pure python package, and doesn't put any version restrictions on its dependencies (https://github.com/conda-forge/contextily-feedstock/blob/421d38e5e1c58a2297e86d548e27f028ae04a0c1/recipe/meta.yaml#L21-L28). So AFAIK it should always be possible to install it with the latest versions of eg fiona.

**Comment by pythonic2020** [comment]
Thank you for your reply.  As I wrote before, 

> installing contextily into a conda-forge environment necessitates downgrading gdal and fiona substantially (to gdal 3.1.4 and fiona 1.8.18).

Here I create a new conda env from scratch to show you what happens:

```
> conda create -n test39 -c conda-forge python=3.9
> conda activate test39
> conda config --env --set channel_priority flexible
> conda config --env --add channels conda-forge
> conda config --env --show channels
channels:
  - conda-forge
  - defaults
> conda update --all
> python -V
Python 3.9.2
> conda install matplotlib pandas numpy geopandas folium
> conda install contextily
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\me\Miniconda3\envs\test39

  added / updated specs:
    - contextily


The following NEW packages will be INSTALLED:

  affine             conda-forge/noarch::affine-2.3.0-py_0
  contextily         conda-forge/noarch::contextily-1.1.0-pyhd8ed1ab_0
  geographiclib      conda-forge/noarch::geographiclib-1.50-py_0
  geopy              conda-forge/noarch::geopy-2.1.0-pyhd3deb0d_0
  joblib             conda-forge/noarch::joblib-1.0.1-pyhd8ed1ab_0
  mercantile         conda-forge/noarch::mercantile-1.2.1-pyhd8ed1ab_0
  rasterio           conda-forge/win-64::rasterio-1.2.1-py39hfec4536_0
  snuggs             conda-forge/noarch::snuggs-1.4.7-py_0

The following packages will be DOWNGRADED:

  fiona                               1.8.19-py39h9f1b043_0 --> 1.8.18-py39he2373ac_0
  gdal                                 3.2.2-py39h6795fcd_3 --> 3.1.4-py39haafd053_13
  libgdal                                  3.2.2-hade8cfc_3 --> 3.1.4-hade8cfc_13


Proceed ([y]/n)?
```
The DOWNGRADED section shows the required downgrade of gdal and fiona.  Not a big deal, but I thought I'd inquire about it.

------------------------------------------------------------

I installed _contextily_ (and later _mapclassify_ and _rasterstats_) to follow your **excellent** DataCamp course on geospatial data in Python! I loved the course.  My main interest is with raster data, so I wish there was more content on handling rasters, but I had great fun anyway.  As you didn't supply the African landuse/landcover raster dataset used in the course, I downloaded a similar dataset from EarthExplorer and used rasterio and shapely to 1) reproject it from Lambert Equal Area to EPSG 4326 and 2) subset it based on combined extents of artisinal mine and national park vector datasets.  An idea: it would save user time by providing both the African LU/LC subset and the national park dataset.  I found the national park dataset on your Github scipy2018-geospatial-data repo, however.  

Are there any online courses on analysis of raster satellite/airborne spectral imagery in Python that you would recommend, especially courses involving Deep Learning?

Keep up your great work!  :-)

**Comment by darribas** [comment]
Hello @pythonic2020, thanks for your comment and for the issue. As @jorisvandenbossche mentions, `contextily` does not impose any requirements on dependencies. Could the behaviour you're observing be related to the underlying libs? Can you for example install `rasterio` without those same downgrades? My sense is that this behaviour relates to installing in the same env `geopandas` and `rasterio`?

I'm closing for now but feel free to reopen if needed.
