### ISSUE TITLE
Add `zoom_adjust` to `add_basemap`

### ISSUE THREAD

**Issue by darribas** [geopandas/contextily#188]
It'd be great to give the flexibility that `zoom_adjust` provides in the `Place` API:

https://github.com/geopandas/contextily/blob/5b560f9f64aeff238878df7d5cac902ed7973f3e/contextily/place.py#L36-L38

to `add_basemap`. That way, the user could fine tune basemaps more easily.

**Comment by martinfleis** [comment]
Closed by #228
