### ISSUE TITLE
Caching and terms of service? 

### ISSUE THREAD

**Issue by ljwolf** [geopandas/contextily#202]
Over at [gdsbook/book](https://github.com/gdsbook/book), we use `contextily` to provide basemaps for many of the maps in our book. 

As part of the pre-publication review process, I went through each image we create and tried to make sure that we have license to use all the information in the image. 

As a part of this, I had to look into our use of CARTO Positron & Voyager basemaps through contextily (e.g. [chapter 8](https://geographicdata.science/book/notebooks/08_point_pattern_analysis.html)). This led me to the [CARTO Basemap Terms of Service](https://drive.google.com/file/d/1P7bhSE-N9iegI398QYDjKeVhnbS7-Ilk/view), which I had to read & understand in order to check if we can use these basemaps in our book. [I'm uploading them here, too, in case the site goes down for some reason.](https://github.com/geopandas/contextily/files/9754246/CARTO.Terms.of.Service.-.Basemaps.-.2021.02.15.pdf)

I note that in Page 4, point 9c in the **Acceptable Use Policy**, states:

> Customer agrees to not engage in the following unacceptable uses of the Basemap Services:
> storing, saving, or redistributing any map content from the Basemap Services, including from a cache or
temporary storage, or by using a screenshot or other static image instead of directly accessing via CARTO’s
APIs;

I'm raising this here, because (as I read it) this may potentially conflict with our [automatic caching](https://github.com/geopandas/contextily/blob/72c85a1097dfad6f03d2b0b17cd92dfd8171b0ee/contextily/tile.py#L42) of tiles in a single session... What do developers think about this?

I think a "safe" solution to this would be to disable caching for basemaps with non-CC licenses, or just document this and make sure the user is responsible for when to cache and when not.

**Comment by martinfleis** [comment]
I would add an option to control whether to use caching or not ensuring that we have a way of conforming to ToS like this one. But I would eventually only document the behaviour and let a user to turn it off manually, leaving the responsibility on a user side.

**Comment by martinfleis** [comment]
Closed by #217
