### ISSUE TITLE
Wrong lat and lon from contextily bbox

### ISSUE THREAD

**Issue by automataIA** [geopandas/contextily#207]
I write this code:

```
sind = Place("Sindian")
print(sind.bbox_map)
```
and the output is:
`(13516512.585724287, 13540972.434775542, 2856910.369186746, 2876478.248427753)`

But the coordinate for example are, circa:
(25.014 , 121.473)

Why?

**Comment by darribas** [comment]
Closing as I _think_ this is answered, but happy to engage further if there's any additional question.
