### ISSUE TITLE
Save as editable object

### ISSUE THREAD

**Issue by annika-stechemesser** [geopandas/contextily#218]
I'm using contextily to create maps for a project and it works great. However, one of the requirements is that the final plot needs to be editable (i.e. .eps, .ai, .svg, .pdf tile). When I save as PDF my annotations are editable but not the tile. When I save as .eps or .svg the plots come up completely blank. What am I doing wrong? Thank you!

**Comment by martinfleis** [comment]
Tiles are rasters coming usually as PNG. You will never get it as an editable geometry.

**Comment by darribas** [comment]
@annika-stechemesser, as @martinfleis says, this is a feature of the source data rather than `contextily`, we're just pulling down the tiles which, in this case, are image files (typically JPEG).
