### ISSUE TITLE
Change the default basemap from Stamen

### ISSUE THREAD

**Issue by martinfleis** [geopandas/contextily#220]
contextily now uses Stamen Terrain as a default. With [Stamen deprecating their tiles](https://stamen.com/here-comes-the-future-of-stamen-maps/), this will need to change. Any preference? I think the feasible options are OpenStreetMap tiles or some Carto tile. cc @darribas

**Comment by ianthetechie** [comment]
Hey @martinfleis, I'm one of the cofounders of Stadia Maps. Funny enough, my sister is doing a data science project right now and is using contextily, which missed our pass through the major FOSS projects using the Stamen tiles 😂 

The Stamen styles will still be available (with updated data coming in the next week or so!) via Stadia Maps, but will require a (free with generous limits for non-commercial use) API key. It looks like you already have an integration for our other styles, so it shouldn't be too difficult to add more.

We've put together a migration guide here: https://docs.stadiamaps.com/guides/migrating-from-stamen-map-tiles/. I'd be happy to take a whack at a PR if that'd be helpful.

Either way, I totally understand setting the default to a provider which doesn't require an API key; that makes for a better dev experience. The Carto styles are great in my experience, and you can see the influence of Stamen's cartography both in some of their styles and our own Alidade Smooth.

**Comment by martinfleis** [comment]
@ianthetechie Yes, we do have the full support of Stadia tiles already, including Stamen once I cut a release of xyzservices, we just need the default to "just work".
