### ISSUE TITLE
Input array error when loading contextily basemap

### ISSUE THREAD

**Issue by FrancescaPontin** [geopandas/contextily#226]
Discovered by one of my students, there looks to be a new bug when using contextily to add background maps to plots. 

"could not broadcast input array from shape (512,512,4) into shape (256,256,4)"

A similar issue has been reported here
- https://gitlab.com/deltares/imod/imod-python/-/issues/567

The same error is evident in the geopandas gallery. 
- https://geopandas.org/en/latest/gallery/plotting_basemap_background.html 

I was wondering if anyone had any thoughts as to the cause (OpenStreetMap?)

**Comment by martinfleis** [comment]
Thanks for the report! See https://github.com/geopandas/contextily/issues/223 for the analysis and solutions.
