### ISSUE TITLE
Stamen not available as a valid provider

### ISSUE THREAD

**Issue by Naarlack** [geopandas/contextily#234]
Perhaps I'm doing something wrong, but I have not been able to get a Stamen map to work as shown throughout the docs.

Stamen does not appear as a listed option when I run `contextily.providers`.

I did some digging into xyzservices and, from what I can tell, the Stamen maps are now listed under the Stadia provider. However, calling `Stadia.StamenToner` (for example) results in blank tiles showing an error has occurred.

**Comment by Naarlack** [comment]
I found an explanation here:  https://github.com/leaflet-extras/leaflet-providers?tab=readme-ov-file#stamen-design

It's probably a good idea to make this known in the documentation and update examples that show code which will no longer work.

**Comment by martinfleis** [comment]
Thanks for the heads up. We have actually already fixed all of this a while ago and removed Stamen from docs but I just now realised, that our docs are not rendering currently so the changes never made it to the documentation website. Will fix that.
