### ISSUE TITLE
os.wait fails in tile.py

### ISSUE THREAD

**Issue by cragm** [geopandas/contextily#244]
I expect `os.wait(wait)` at line 447 in tile.py will always fail.

In Windows, I expect something like:

> AttributeError: module 'os' has no attribute 'wait'

In Linux (and presumably MacOS), I expect something like:

> TypeError: posix.wait() takes no arguments (1 given)

This seems to be consistent with the standard library documentation [https://docs.python.org/3/library/os.html#os.wait](https://docs.python.org/3/library/os.html#os.wait)

Given the context, I assume `time.sleep(wait)` would provide something closer to the intended outcome. [https://docs.python.org/3/library/time.html#time.sleep](https://docs.python.org/3/library/time.html#time.sleep)

Apologies, if I'm missing something. I'd been using Contextily for a while and only noticed this problem when some internet gremlin happened to lead to the invocation of line 447. Thanks!

**Comment by martinfleis** [comment]
Good catch! This is nearly impossible to test. Will push a fix.
