### ISSUE TITLE
Several errors with ctx.add_basemap()

### ISSUE THREAD

**Issue by veenstrajelmer** [geopandas/contextily#247]
I am using `ctx.add_basemap()` to spice up an [example notebook](https://github.com/Deltares/dfm_tools/blob/main/docs/notebooks/modelbuilder_example.ipynb) for a package I maintain. This package/function is really helpful so thanks for creating this. However, it is convenient if my notebook runs successfully at any moment in time, independent of contextily. Quite often, the notebook crashes because of a (server)timeout or different error in contextily that temporarily pops up. Today, I encountered the following error, which is not really reproducible at the moment:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 15
     13 mk_object.mesh2d_get().plot_edges(ax,zorder=1)
     14 bnd_gdf_interp.plot(ax=ax, edgecolor='r')
---> 15 ctx.add_basemap(ax=ax, crs=crs, attribution=False)
     16 dfmt.plot_coastlines(ax=ax, crs=crs)

File ~\Anaconda3\envs\dfm_tools_env\Lib\site-packages\contextily\plotting.py:134, in add_basemap(ax, zoom, source, interpolation, attribution, attribution_size, reset_extent, crs, resampling, zoom_adjust, **extra_imshow_args)
    130     left, right, bottom, top = _reproj_bb(
    131         left, right, bottom, top, crs, "epsg:3857"
    132     )
    133 # Download image
--> 134 image, extent = bounds2img(
    135     left, bottom, right, top, zoom=zoom, source=source, ll=False, zoom_adjust=zoom_adjust
    136 )
    137 # Warping
    138 if crs is not None:

File ~\Anaconda3\envs\dfm_tools_env\Lib\site-packages\contextily\tile.py:265, in bounds2img(w, s, e, n, zoom, source, ll, wait, max_retries, n_connections, use_cache, zoom_adjust)
    262 arrays = Parallel(n_jobs=n_connections, prefer=preferred_backend)(
    263     delayed(fetch_tile_fn)(tile_url, wait, max_retries) for tile_url in tile_urls)
    264 # merge downloaded tiles
--> 265 merged, extent = _merge_tiles(tiles, arrays)
    266 # lon/lat extent --> Spheric Mercator
    267 west, south, east, north = extent

File ~\Anaconda3\envs\dfm_tools_env\Lib\site-packages\contextily\tile.py:660, in _merge_tiles(tiles, arrays)
    657 indices = tile_xys - tile_xys.min(axis=0)
    659 # the shape of individual tile images
--> 660 h, w, d = arrays[0].shape
    662 # number of rows and columns in the merged tile
    663 n_x, n_y = (indices + 1).max(axis=0)

AttributeError: 'NoneType' object has no attribute 'shape'
```

I think this should be possible to reproduce this with this simpler code:
```python
import matplotlib.pyplot as plt
plt.close('all')
import contextily as ctx

lon_min, lon_max, lat_min, lat_max = 105.8, 106.85, 17.75, 18.5

fig, ax = plt.subplots()
ax.set_xlim(lon_min, lon_max)
ax.set_ylim(lat_min, lat_max)

ctx.add_basemap(ax=ax, crs='EPSG:4326')
```

I understand that this is not a useful issue description since it is not reproducible yet. However, I would like to have it as a placeholder so I can immediately report related follow-up issues in the future. Feel free to close it as "won't do", it can be re-opened when relevant. My ideal situation would be that this function is more robust and does not crash every few weeks. Until then, I will comment usage in my example notebook in order to not bother users with it.

**Comment by martinfleis** [comment]
Hi, I am aware of these issues but their unpredictable nature makes it very tricky to reproduce and fix them. I have never been able to reproduce it locally.

I learned that it is way more often caused by the default OpenStreetMap.HOT tile provider than other, so for the sake of stability of your documentation, I would suggest picking another provider. That should fix the issue in most cases. 

The problem is that when requesting a tile from a provider, we don't receive data. It is not a bug on contextily side but on the server side we cannot influence. We could try to re-try the tile fetching if it returns null array but I would need to reproduce the issue to write that fix reliably.

**Comment by veenstrajelmer** [comment]
Thanks for this clarification, it makes total sense. It would still be great if the error can be more meaningful than `AttributeError: 'NoneType' object has no attribute 'shape'` though. In the current situation I see often it is difficult for users to realize that it is due to a server fault, which makes sense to me.

**Comment by veenstrajelmer** [comment]
I am now getting this one:
```python
Traceback (most recent call last):

  File ~\Anaconda3\envs\dfm_tools_env\Lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\data\dfm_tools\dfm_tools\untitled2.py:18
    ctx.add_basemap(ax=ax, crs='EPSG:4326')

  File ~\Anaconda3\envs\dfm_tools_env\Lib\site-packages\contextily\plotting.py:134 in add_basemap
    image, extent = bounds2img(

  File ~\Anaconda3\envs\dfm_tools_env\Lib\site-packages\contextily\tile.py:265 in bounds2img
    merged, extent = _merge_tiles(tiles, arrays)

  File ~\Anaconda3\envs\dfm_tools_env\Lib\site-packages\contextily\tile.py:660 in _merge_tiles
    h, w, d = arrays[0].shape

AttributeError: 'NoneType' object has no attribute 'shape'
```

This comes from the `_merge_tiles()` function, just like my initial issue description, but another line. I think now `array[0]` is `None`, while before `array[n]` was `None`. I think it would be valuable to add this code to `_merge_tiles()`:
```python
if None in arrays:
    raise ValueError('None was returned by the server when retrieving image tiles/arrays, please try again or later')
```

Or maybe better, add this to `_fetch_tile()` or even to `_retryer()`:
```python
if array is None:
    raise ValueError('None was returned by the server when retrieving image array, please try again or later')
```

This way, at least it is clear for the user that this is because of a server issue.

Unfortunately this was all the testing I could do since after these steps, the returned tiles were complete again.

**Comment by martinfleis** [comment]
That is a great analysis! Could you try to turn these into a pull request? I don't really have a bandwidth to look into that myself but I should be able to review it.

**Comment by veenstrajelmer** [comment]
I know now why the `is None` check does not work in `_retryer()` but does work in `_fetch_tile()`. This is because the request part works fine, but sometimes there is a `HTTPError` like this:
```
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://a.tile.openstreetmap.fr/hot/10/815/459.png
```
This is not catched by the if/elif loop under except. Adding `502` to the list would fix this specific problem, but actually I guess it should just be an `else` instead of `elif`, so all status_codes that are not 404 are tried again. What do you think?

**Comment by martinfleis** [comment]
> I guess it should just be an else instead of elif

that is probably right.

I also think, that occasionally we get status 200 but `image` and then `array` are empty. We should check for that in `_retryer`, ensuring that if we return a tile, it is valid.

**Comment by veenstrajelmer** [comment]
In all testing I did I did not encounter an empty `array` in `_retryer`, that is what confused me at first. But later I noticed it is none because not all situations are captured, after which the function returns None which can be then seen in `_fetch_tiles()`. Could it not be that those occasions you mention were also status_codes different that 404/200/104?

**Comment by veenstrajelmer** [comment]
> I also think, that occasionally we get status 200 but `image` and then `array` are empty. We should check for that in `_retryer`, ensuring that if we return a tile, it is valid.

It seems you are right, I just saw this happening despite the fix from the PR:
```
/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/contextily/plotting.py:134: in add_basemap
    image, extent = bounds2img(
/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/contextily/tile.py:287: in bounds2img
    merged, extent = _merge_tiles(tiles, arrays)
/opt/hostedtoolcache/Python/3.12.5/x64/lib/python3.12/site-packages/contextily/tile.py:682: in _merge_tiles
    h, w, d = arrays[0].shape
E   AttributeError: 'NoneType' object has no attribute 'shape'
```

But of course very difficult to reproduce and therefore to check whether a potential fix is indeed correct. It strikes me how instable the default source has become, this was not the case several months ago. Is there someone who can be contacted about this? Or is it maybe wise to consider another default source?

**Comment by martinfleis** [comment]
It is happening since the release of 1.5.0 in December which changed the default from Stamen tiles that no longer work without an API key to OpenStreetMap.HOT. Their servers seems to be a bit flaky.

One option is to change the default again, to OpenStreetMap.Mapnik, which I suppose will be much more stable but also less suited to be used as a background map due to its cartographic style. Other option is to catch the error above in a similar way we did with the other points of failure and raise the same error explaining that this is not a contextily issue. But given the relative frequency, it may be the best to switch the default again, even if it may cause some friction for downstream users.

**Comment by martinfleis** [comment]
cc @jorisvandenbossche this is the issue we've been discussing yesterday.

**Comment by veenstrajelmer** [comment]
Follow-up issue to also catch this None: https://github.com/geopandas/contextily/issues/252

**Comment by martinfleis** [comment]
No. Folks from Stadia were doing fixes across the ecosystem to allow Stamen tiles to be pulled via Stadia, which we do allow. But for that you need a Stadia API key, so it is not suitable for a default style.

**Comment by veenstrajelmer** [comment]
Agreed, shame that they added this API-key..

**Comment by veenstrajelmer** [comment]
> One option is to change the default again, to OpenStreetMap.Mapnik, which I suppose will be much more stable but also less suited to be used as a background map due to its cartographic style. Other option is to catch the error above in a similar way we did with the other points of failure and raise the same error explaining that this is not a contextily issue. But given the relative frequency, it may be the best to switch the default again, even if it may cause some friction for downstream users.

By the way, I also got the HTTPError with OpenStreetMap.Mapnik, so I guess updating the default to that does not make a lot of sense. Would it be worthwile to report it? I would not know where, but you might have an idea?

**Comment by martinfleis** [comment]
No idea where, never looked for it.
