### ISSUE TITLE
check scaling of basemaps and axis

### ISSUE THREAD

**Issue by veenstrajelmer** [geopandas/contextily#251]
I noticed that the contextily basemap scales my figure axes significantly more than a geopandas object does. This is documented for my tool here: https://github.com/Deltares/dfm_tools/issues/966. Is this something that you recognize or is this even intented? I am curious to hear. If it is unexpected I can share an example with less dependencies.

**Comment by martinfleis** [comment]
Would you be able to provide a reproducible example? GeoPandas sets aspect to equal for projected CRS and to [custom](https://github.com/geopandas/geopandas/blob/aafd7b5fad392f5f77dd0b13f8cfa3bc1db72d6c/geopandas/plotting.py#L381-L387) for geographical. Contextily does not change the aspect afaik but it does assume equal due to pixels of the underlying tile image being square. Could be a result of some interplay between these but a minimal example would help here.

**Comment by veenstrajelmer** [comment]
```python
import matplotlib.pyplot as plt
plt.close('all')
import contextily as ctx
import geopandas as gpd


def xy_convert_crs(xmin, xmax, ymin, ymax, crs_from, crs_to):
    """
    convert xlim/ylim from WGS84 to output crs
    """
    bbox_points = gpd.points_from_xy(x=[xmin, xmax], y=[ymin, ymax], crs=crs_from)
    bbox_points = bbox_points.to_crs(crs_to) #convert to new crs
    [xmin, xmax] = bbox_points.x
    [ymin, ymax] = bbox_points.y
    return xmin, xmax, ymin, ymax


def plot_coastlines(ax, crs=None):
    
    xlim = ax.get_xlim()
    ylim = ax.get_ylim()
    
    xmin, xmax = xlim
    ymin, ymax = ylim
    # xmin, xmax, ymin, ymax = -180, 180, -90, 90
    if crs is not None:
        xmin, xmax, ymin, ymax = xy_convert_crs(xmin, xmax, ymin, ymax, 
                                                crs_from=crs, crs_to='EPSG:4326')

    # attached, but the full gshhg-shp-2.3.7.zip can also be retrieved from https://www.ngdc.noaa.gov/mgg/shorelines/data/gshhg/latest/
    file_shp = r"c:\Users\veenstra\Downloads\gshhg-shp-2.3.7\GSHHS_shp\c\GSHHS_c_L1.shp"
    bbox = (xmin, ymin, xmax, ymax)
    coastlines_gdb = gpd.read_file(file_shp, columns=[], bbox=bbox)
    
    if crs:
        coastlines_gdb = coastlines_gdb.to_crs(crs)
    
    coastlines_gdb.plot(ax=ax, edgecolor='k', facecolor='none', zorder=5)
    
    ax.set_xlim(xlim)
    ax.set_ylim(ylim)


lon_min, lon_max, lat_min, lat_max = -6, 3.5, 48, 51.5 # france

plot_crs = 'EPSG:4326'
# plot_crs = 'EPSG:3857'

lon_min, lon_max, lat_min, lat_max = xy_convert_crs(lon_min, lon_max, lat_min, lat_max, 
                                                    crs_from='EPSG:4326', crs_to=plot_crs)

fig, (ax1, ax2) = plt.subplots(2,1)
ax1.set_xlim(lon_min, lon_max)
ax1.set_ylim(lat_min, lat_max)
ctx.add_basemap(ax=ax1, crs=plot_crs, attribution=False)
plot_coastlines(ax=ax1, crs=plot_crs)

ax2.set_xlim(lon_min, lon_max)
ax2.set_ylim(lat_min, lat_max)
plot_coastlines(ax=ax2, crs=plot_crs)
ctx.add_basemap(ax=ax2, crs=plot_crs, attribution=False)
```

With `plot_crs = 'EPSG:4326'` (different aspect):
![image](https://github.com/user-attachments/assets/ff7901bb-7884-468f-aa36-bf4a4a3bd84f)

With `plot_crs = 'EPSG:3857'` (equal aspect):
![image](https://github.com/user-attachments/assets/bcc8bf26-1d17-41ee-b6ed-b871db9d2e49)

With `plot_crs = 'EPSG:4326'` and `xmin, xmax, ymin, ymax = -180, 180, -90, 90` (very comparable aspect):
![image](https://github.com/user-attachments/assets/21bdd8ef-2dd9-4a84-adec-64dc5b6e7a00)

Creating this reproducible code helped me better understanding the issue (as always). It seems that the scaling is different depending on the bounding box of the object to be plotted. It seems that this bounding box for contextily images is always the full globe, but in this coastlines example this is sometimes different (this makes reading significantly faster for higher resolutions). So I guess I figured it out why the differences occur and how to avoid these. However, I still not fully get why the scaling is different depending on the bounding box. If it makes sense, would it then not also make sense to make the scaling dependent on the area that is plotted instead of the entire globe?

Feel free to close this issue, but some additional clarification is welcome.

The shapefile with coastlines:
[gshhg-shp-2.3.7_coarse_only.zip](https://github.com/user-attachments/files/16822571/gshhg-shp-2.3.7_coarse_only.zip)

**Comment by martinfleis** [comment]
Thanks! What happens here is that when using EPSG 4326, GeoPandas tried so set the aspect to minimise distortion of geometries which are represented in degrees on a sphere. And contextily resets the aspect to 1:1. We should probably avoid doing that but given it is not done explicitly, not sure how easy that is.

**Comment by veenstrajelmer** [comment]
Amazing, thanks for fixing this!
