### ISSUE TITLE
Move project to organisational account?

### ISSUE THREAD

**Issue by darribas** [geopandas/contextily#28]
I think, going forward, the project should find a better home than my personal account. I'm pretty agnostic to where, but my suspicion is that either [geopandas](https://github.com/geopandas) or [PySAL](https://github.com/pysal) would be good candidates. What do you think @choldgraf, @ljwolf, @jorisvandenbossche, @sjsrey?

**Comment by choldgraf** [comment]
+1

Also I believe I've seen you here @ scipy, yes?

**Comment by sjsrey** [comment]
Happy to have it on the [pysall](https://github.com/pysal) org repos if that helps.

**Comment by darribas** [comment]
@choldgraf Yes! Let's connect!

**Comment by darribas** [comment]
This has been moved to the `geopandas` account.
