### ISSUE TITLE
Doc updates pre 1.0

### ISSUE THREAD

**Issue by darribas** [geopandas/contextily#37]
The following needs to be added to make the new features exposed to the public:

* Add use of `add_basemap` to the guide notebook
* Update the `Place.plot()` changes
* Update `README.md`

**Comment by jorisvandenbossche** [comment]
Something else that would be nice is to have a page showing all the default provided tile sources (eg showing same figure with each source)

**Comment by darribas** [comment]
@jorisvandenbossche, yes, there's a ticket (#27) to write  a small method that pulls in all of the available sources. When done, we could then have it generate a HTML/md file that can be easily accessed here on GH.

**Comment by datapolitan** [comment]
You should probably also add that to get `add_basemap()` you need to use `pip3 install contextily==1.0rc2`. As the documentation reads now, I think it's easy to think (as I did) that just doing `pip3 install contextily` will provide `add_basemap()`.

**Comment by darribas** [comment]
YEs, I think we should really just push 1.0 :-) We're all a bit tied for time but my sense is that we need to leave stable the `providers` infrastructure, then I'd be happy to push it out.

As for the note for how to install `rc2`, of course, PRs welcome! :-)

**Comment by datapolitan** [comment]
@darribas Done.
