### ISSUE TITLE
[ENH] Modify `add_basemap` for local windowed reading

### ISSUE THREAD

**Issue by darribas** [geopandas/contextily#86]
Currently, when the user points to a local file on `add_basemap`, the file is fully read and then clipped/zoomed on to the extent `ax` was passed on. For cases where a raster is too large, it'd be nice to provide an option so that only the required window is read from the local raster file. This would make `add_basemap` a very easy method to plot parts of large rasters (e.g. world night lights) as basemaps.

Pointers:

- Code should be implemented on [L.96-`plottint.py`](https://github.com/darribas/contextily/blob/master/contextily/plotting.py#L96) to avoid always reading the full file first.
- Potential code to use for windowed reading from `rasterio` masking functionality ([`URL`](https://rasterio.readthedocs.io/en/stable/topics/masking-by-shapefile.html))

To think about:

- Should we let the user choose to read the whole file and adapt the the extent of `ax` accordingly? This might fit other use cases.
- What'd be the best API to enable this functionality? I'm thinking an additional argument on `add_basemap` such as `read_full=False` that, when `True` reads the whole file and adjusts the axis extent, otherwise in only reads a window for the extent of `ax`?

**Comment by jorisvandenbossche** [comment]
To avoid to add yet another keyword (and one that is only valid depending on the value of another keyword), we could also reuse `reset_extent` for this? 
If `reset_extent=True` (default), we can read only the needed part of the raster file, as the rest is not shown on the figure anyhow. 
If `reset_extent=False`, we of course read the full raster, as we use in this case the extent of the raster as extent of the figure.

**Comment by darribas** [comment]
GReat idea! +1

**Comment by darribas** [comment]
Addressed in #129
